
[[dependencies]]
  branch = "master"
  name = "github.com/BurntSushi/toml"

[[dependencies]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[dependencies]]
  name = "github.com/containers/virtcontainers"
  revision = "267bb85ffc5206a5a6cf934828a1a54ac9e99038"

[[dependencies]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "a5c4e91dae9533c46a98f122b5085c0b3fe27ee4"

[[dependencies]]
  branch = "master"
  name = "github.com/urfave/cli"
