[[constraint]]
  name = "github.com/BurntSushi/toml"
  revision = "a368813c5e648fee92e5f6c30e3944ff9d5e8895"

[[constraint]]
  name = "github.com/dlespiau/covertool"
  revision = "b0c4c6d0583aae4e3b5d12b6ec47767670548cc4"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "a0159fddcd197a57790b6dd5654802b7dc8f80be"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "89742aefa4b206dcf400792f3bd35b542998eb3b"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "890a5c3458b43e6104ff5da8dfa139d013d77544"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "9e5b04886c4bfee2ceba1465b8121057355c4e53"

[[constraint]]
  name = "github.com/kata-containers/runtime"
  revision = "167d54a5ce654104f3a2cd76d54d46d2cafd3016"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
